apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: min-cluster
spec:
  general:
    version: 2.2.0
    httpPort: 9200
    defaultRepo: "docker.io/nosqlpass"
    vendor: opensearch
    serviceName: min-cluster
  #    pluginsList: ["repository-s3"," https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/1.3.0.0/prometheus-exporter-1.3.0.0.zip"]
  dashboards:
    version: 2.2.0
    enable: true
    replicas: 2
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 2
      diskSize: "50Gi"
      NodeSelector:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      roles:
        - "cluster_manager"
    - component: nodes
      replicas: 2
      diskSize: "50Gi"
      NodeSelector:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      roles:
        - "data"