apiVersion: opensearch.opster.io/v1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  replicas: 1
  config:
    openSearchClusterRef:
      name: my-cluster
      service: my-cluster
      secret: my-cluster-admin-password
    #   namespace: defaults
    logstashConfig:
      - name: env1
        value: "hehe1"
      - name: env2
        value: "haha2"
    ports: [8080, 9600]
    # pipelineConfig:
    #   inputs:
    #   filters:
    #   outputs:
    #   openSearchIndex:
  podTemplate:
    spec:
      containers:
        - name: logstash