apiVersion: opensearch.opster.io/v1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  replicas: 1
  config:
    opensearchClusterName: opscluster
    logstashConfig:
    ports: [9001,9002]
    pipelineConfig:
      inputs:
        - file:
            "path => abc"
            "other => def"
      filters:
      outputs:
  podTemplate:
    spec:
      containers:
        - name: logstash