apiVersion: opensearch.opster.io/v1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  replicas: 2
  config:
    jvm: "-Xms512m -Xmx512m"
    openSearchClusterRef:
      name: my-cluster
      service: my-cluster
      secret: my-cluster-admin-password
      namespace: default
    logstashConfig:
      - name: env1
        value: "hehe1"
      - name: env2
        value: "haha2"
    ports: [8080, 9600]
    pipelineConfig:
      inputs:
      filters:
      outputs:
      openSearchIndex: "index => myabc"
  podTemplate:
    spec:
      containers:
        - name: logstash