apiVersion: opensearch.opster.io/v1
kind: Logstash
metadata:
  name: logstash-sample
spec:
  replicas: 1
  config:
    openSearchClusterRef:
      name: opscluster
    #   namespace: defaults
    logstashConfig:
      - name: env1
        value: "hehe1"
      - name: env2
        value: "haha2"
    ports: [9001,9002, 9600]
    # pipelineConfig:
    #   inputs:
    #   filters:
    #   outputs:
    #   openSearchOutput:
  podTemplate:
    spec:
      containers:
        - name: logstash